### ISSUE TITLE
バージョン番号を付けてほしい

### ISSUE THREAD

**Issue by kmyk** [colun/mmlang#2]
参考: https://semver.org/lang/ja/

**Comment by colun** [comment]
ありがとうございます。下記コミットにて対応致しました。他に不具合などありましたら、またご連絡頂けますと助かります。（なお、他のissueに関しては今回対応出来ませんでした。次回以降で検討致します）

https://github.com/colun/mmlang/commit/cc1f9e6e117c431b1b7a0ae68a550dd113077571
