### ISSUE TITLE
xvectorでのfast_arrayの参照方法について

### ISSUE THREAD

**Issue by ao1415** [colun/mmlang#5]
mmlang/lib/xvector.hの以下の部分にて、fast_arrayの::data()を参照していないため、コンパイルエラーが発生しています。

inline xref<T> let_back()関数
Line:69
`return xref<T>(data_ + (count++));`

inline xref<T> front()関数
Line:104
`return xref<T>(data_);`

inline xref<T> back()関数
Line:112
`return xref<T>(data_ + (count-1));`

inline void resize(int n, const T & value)関数
Line:125
`xmem::modify(&data_[count], sizeof(*data_)*(n-count));`

**Comment by ao1415** [comment]
mmlang/lib/xvector.hの以下の部分にて、fast_arrayの::data()を参照していないため、コンパイルエラーが発生しています。

inline xref<T> let_back()関数
Line:69
`return xref<T>(data_ + (count++));`

inline xref<T> front()関数
Line:104
`return xref<T>(data_);`

inline xref<T> back()関数
Line:112
`return xref<T>(data_ + (count-1));`

inline void resize(int n, const T & value)関数
Line:125
`xmem::modify(&data_[count], sizeof(*data_)*(n-count));`

**Comment by colun** [comment]
ありがとうございます。下記コミットにて対応致しました。他に不具合などありましたら、またご連絡頂けますと助かります。

https://github.com/colun/mmlang/commit/cc1f9e6e117c431b1b7a0ae68a550dd113077571
